apiVersion: v1
kind: Service
metadata:
  name: hello-node
  labels:
    example: hello-node
    app: hello-node
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: hello-node
    example: hello-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
  labels:
    app: hello-node
    example: hello-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-node
      example: hello-node
  template:
    metadata:
      labels:
        app: hello-node
        example: hello-node
    spec:
      containers:
      # replace the repository URL with your own repository (e.g. {DockerID}/hello-node:0.0.x for Docker Hub).
      - image: sysintelligent/hello-node
        name: hello-node
        ports:
        - name: http
          containerPort: 3000
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 32Mi